# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=255),
        ),
    ]
