# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_minbtns_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(default=True, upload_to='', verbose_name='头像'),
        ),
    ]
