# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
